---
title: "Sharing data"
author: "Jack Humphrey"
date: "20/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(limma)
library(edgeR)

gene_meta <- read_tsv(here::here("data/misc/gencode.v30.tx2gene.tsv.gz") )%>%
  janitor::clean_names() %>%
  select(genename, geneid) %>%
  distinct() %>%
  mutate( geneid = str_split_fixed(geneid, "\\.", 2)[,1] )

theme_jh <- function () { 
    theme_bw(base_size=10) %+replace% 
        theme(
          panel.grid = element_blank(),
          strip.background = element_blank(),
          #panel.border = element_blank(),
          axis.line = element_line(),
          #text = element_text(color = "black"), 
          strip.text = element_text(color = "black"),
          axis.text = element_text(colour = "black"),
            panel.background  = element_blank(),
            plot.background = element_rect(fill="white", colour=NA), 
            legend.background = element_rect(fill="transparent", colour=NA),
            legend.key = element_rect(fill="transparent", colour=NA), 
            axis.line.y = element_line(), strip.text.x = element_text(face = "bold", margin = margin(t = 2,r = 0,b = 2,l=0))
        )
}


```

## Putting together final file list 

Start with all spinal cord RNA and DNA samples
add column for those used in QTL analysis and for DEG analysis

De-identify samples

Remove age of death and onset


```{r}

rna <- read_tsv(here::here("metadata/rna/rna_metadata_annotated.tsv"))
qtl <- read_tsv(here::here("ALS_SC/tables/all_qtl_samples_used.tsv"))
deg <- read_tsv(here::here("data/differential_expression/ALS/ALS_all_differential_expression_support.tsv"))

sample_table_full <- filter(rna,
                           external_sample_id %in% unique( c(qtl$external_sample_id, deg$sample))
                           ) %>%
  mutate( DEG = external_sample_id %in% deg$sample,
          QTL = external_sample_id %in% qtl$external_sample_id) %>%
  mutate(onset = ifelse(disease == "ALS", onset, NA)) %>%
    mutate(disease_duration = death - onset) %>%
  mutate(age_rounded = signif(as.numeric(age_at_death), 1)) %>%
  mutate(age_rounded = ifelse(is.na(age_rounded), 90, age_rounded ))



# create anonymised versions of donor sample and site - make sure they are consistent
sample_table <- sample_table_full %>%
  select(
    external_sample_id,
    external_subject_id,
    site_specimen_collected, tissue = tissue_clean, age_rounded, age_at_death, age_at_onset = onset, sex, subject_group, disease, site_of_motor_onset, disease_duration, mutations, library_prep = prep, seq_platform = platform, rin, c9orf72_repeat_size = c9_repeat_size,
    differential_expression = DEG, qtl_mapping = QTL) %>%
  mutate(c9orf72_repeat_size = as.numeric(c9orf72_repeat_size)) %>%
  mutate(rna_id = paste0( "sample_", as.numeric(as.factor(external_sample_id) ) ),
         dna_id =  paste0( "donor_", as.numeric(as.factor(external_subject_id) ) ),
         site_id =  paste0("site_", as.numeric(as.factor(site_specimen_collected)) )
         ) %>%
  arrange(tissue,dna_id) 
  

write_tsv(sample_table,
          file = here::here("ALS_SC/tables/all_samples_used_in_study.tsv")
          )

# de-identify contributing site, sample ID and donor ID
deid_df <- sample_table %>%
  select(-external_sample_id, -external_subject_id, -site_specimen_collected, -age_at_death, -age_at_onset) %>%
  select( rna_id, dna_id, site_id, everything() )


write_tsv(deid_df, file = here::here("ALS_SC/tables/all_samples_used_in_study_deidentified.tsv"))



```

Put together RNA counts, TPM and covariates for sharing as tar.gz folder

```{r}
# for each tissue
# de-identify tech_loc and support_loc
# put together DNA covariates and RNA covariates into single covariate table

## add MuSiC cell types
conversion_table <- data.frame(
  short = c("Ast","End", "Mic", "Ex", "Oli", "Per" ),
  title = c("% Astrocytes", "% Endothelial", "% Microglia", "% Neurons", "% Oligodendrocytes", "% Pericytes")
)

deconv_res <- 
  read_tsv(here::here("../NYGC_ALS/data/deconvolution/Mathys_MuSiC_residual_results.tsv")) %>%
  filter(sample != "CGND-HRA-00431") %>%
  select(sample, cell, deconv) %>%
  left_join(conversion_table, by = c("cell" = "short")) %>%
  filter(!is.na(title) ) %>%
  select(-cell) %>%
  pivot_wider(names_from = title, values_from = deconv) 

sample_table <- left_join(sample_table, deconv_res, by = c("external_sample_id" = "sample") )




share_counts_cov <- function(t){
  inFile <- here::here( paste0("data/differential_expression/ALS/", t, ".RData"))
  load(inFile)
  
  # make filtered covariate file
  sample_loc <- sample_table %>% 
    filter( external_sample_id %in% support_loc$sample) %>%
    left_join(support_loc %>% select(sample, starts_with("gPC")), by = c("external_sample_id" = "sample")) %>%
    inner_join(tech_loc, by = c("external_sample_id" = "sample")) %>%
    select(rna_id, dna_id, site_id, everything() ) %>%
    select(-differential_expression, -qtl_mapping, -age_at_death)
  
  # deidentify counts and tpm
  names(counts_loc) <- sample_loc$rna_id[match(names(counts_loc), sample_loc$external_sample_id )]
  names(tpm_loc) <- sample_loc$rna_id[match(names(tpm_loc), sample_loc$external_sample_id )]
  
  # add gene names
  counts_loc <- counts_loc %>% 
    rownames_to_column(var = "ensembl_id") %>% 
    left_join(gene_meta, by = c("ensembl_id" = "geneid")) %>%
    select(ensembl_id, gene_name = genename, everything() ) %>%
    filter(!duplicated(ensembl_id))
  
  tpm_loc <- tpm_loc %>% 
    rownames_to_column(var = "ensembl_id") %>% 
    left_join(gene_meta, by = c("ensembl_id" = "geneid")) %>%
    select(ensembl_id, gene_name = genename, everything() ) %>%
    filter(!duplicated(ensembl_id))
  
  # deidentify support
  sample_loc <- select(sample_loc, -external_sample_id, -external_subject_id, -site_specimen_collected)
  
  # test - can I replicate the original DE analysis using just the tables?
  
  outFolder <- paste0(here::here("ALS_SC/sharing/"), t, "/")
  # write out
  dir.create(outFolder, showWarnings = FALSE )
  
  counts_out <- paste0(outFolder, t, "_gene_counts.tsv.gz")
  tpm_out <- paste0(outFolder, t, "_gene_tpm.tsv.gz")
  support_out <- paste0(outFolder, t, "_metadata.tsv.gz")
  
  write_tsv(sample_loc, file = support_out)
  write_tsv(tpm_loc, file = tpm_out)
  write_tsv(counts_loc, file = counts_out)
}
tissues <- c("Cervical_Spinal_Cord", "Lumbar_Spinal_Cord", "Thoracic_Spinal_Cord")
walk(tissues, share_counts_cov)

## include gene name key
write_tsv(gene_meta, file = "ALS_SC/sharing/gencode.v30.gene_meta.tsv.gz")
```





Try replicating results using only the sharing data

```{r}




t <- "Thoracic_Spinal_Cord"
#t <- "Cervical_Spinal_Cord"

outFolder <- paste0(here::here("ALS_SC/sharing/"), t, "/")
counts_out <- paste0(outFolder, t, "_gene_counts.tsv.gz")
tpm_out <- paste0(outFolder, t, "_gene_tpm.tsv.gz")
support_out <- paste0(outFolder, t, "_metadata.tsv.gz")

sample_loc <- read_tsv(support_out)
tpm_loc <- read_tsv(tpm_out)
counts_loc <- read_tsv(counts_out)

support_loc <- as.data.frame(sample_loc)
row.names(support_loc) <- support_loc$rna_id

genes_loc <- counts_loc %>% select(-gene_name) %>% column_to_rownames("ensembl_id")
tpm_df <- tpm_loc %>% select(-gene_name) %>% column_to_rownames("ensembl_id")

# tpm_df["ENSG00000183878",] %>%
#   rownames_to_column("gene") %>%
#   pivot_longer(names_to = "rna_id", values_to = "TPM", cols = !c(gene)) %>%
#   left_join(support_loc, by = c("rna_id") ) %>%
#   ggplot(aes(x = sex, y = TPM)) + geom_boxplot() + geom_point()

keep.exp <- rowSums(tpm_df > 0.01) >= ceiling(0.5 * ncol(genes_loc)) 
# important! CHIT1 is removed at 90%; CHAT at 0.5
genes_loc <- genes_loc[keep.exp, row.names(support_loc)]

support_loc$rin_squared <- support_loc$rin^2
support_loc$age_squared <- support_loc$age_rounded^2
cols <- c("sex", "site_id", "disease", "library_prep")
support_loc <- support_loc %>% mutate_at(cols, funs(factor(.)))
support_loc$disease <- factor(support_loc$disease, levels = c("Control", "ALS"))

# put back age for now
support_loc$age <- as.numeric(sample_table$age_at_death[match(support_loc$rna_id, sample_table$rna_id)])
support_loc <- mutate(support_loc, age = replace_na(age, median(age, na.rm = TRUE) ) )
support_loc$age_squared <- support_loc$age^2


#design1a  <- "~ disease + sex + rin + rin_squared + age + age_squared + prep + gPC1 + gPC2 + gPC3 + gPC4 + gPC5 "
if( t == "Thoracic_Spinal_Cord"){
    design_formula <- as.formula("~ disease + sex + rin + rin_squared + age + age_squared + library_prep + gPC1 + gPC2 + gPC3 + gPC4 + gPC5 + pct_mrna_bases")

}else{
    design_formula <- as.formula("~ disease + sex + rin + rin_squared + age + age_squared + library_prep + site_id + gPC1 + gPC2 + gPC3 + gPC4 + gPC5 + pct_mrna_bases")
}
#design_formula <- as.formula("~ disease + sex + library_prep + age + age_squared + site_id + gPC1 + gPC2 + gPC3 + gPC4 + gPC5 + rin + rin_squared + pct_mrna_bases + pct_chimeras + pct_ribosomal_bases +  pct_intergenic_bases + median_3prime_bias + median_5prime_bias + pct_r1_transcript_strand_reads + pct_adapter")

design_loc <- model.matrix(design_formula, data = support_loc)
  
stopifnot( nrow(support_loc) == nrow(design_loc))
  
# quantile normalise counts
#genes_loc <-  EDASeq::betweenLaneNormalization(as.matrix(genes_loc),which = "full")
# normalized counts with TMM
norm_loc <- calcNormFactors(genes_loc, method = "TMM") 

dge <- DGEList(counts=genes_loc, samples=support_loc, norm.factors = norm_loc)  

v <- voom(dge, design_loc)
vfit <- lmFit(v, design_loc)
efit <- eBayes(vfit)
print(summary(decideTests(efit,adjust.method = "BH", p.value  = "0.05")))


res <- 
    topTable(efit, coef=2, number = Inf, adjust.method = "BH") %>% 
      as.data.frame() %>%
      rownames_to_column(var = "geneid") %>%
      left_join(gene_meta, by = "geneid") %>%
      janitor::clean_names() %>%
      as_tibble() %>%
  arrange(adj_p_val)

table(res$adj_p_val < 0.05)
table(res$adj_p_val < 0.05 & abs(res$log_fc) > 1)


filter(res, genename %in% c("CHAT", "ISL1", "MNX1"))
# # GPNMB
# gpnmb <- filter(gene_meta, genename == "GPNMB") %>% pull(geneid)
# 
# genes_loc[gpnmb,] %>% as.data.frame() %>% rownames_to_column(var = "rna_id") %>%
#   rename(GPNMB = ".") %>%
#   left_join(support_loc, by = "rna_id") %>%
#   ggplot(aes(x = disease, y = GPNMB)) + geom_boxplot()
#  


```




For making the summary table

```{r}
d <- filter(sample_table_full, DEG == TRUE)

d <- mutate(d, disease_group = case_when(disease == "Control" ~ "Control", disease == "ALS" & mutations != "C9orf72" ~ "ALS", disease == "ALS" & mutations == "C9orf72" ~ "ALS-C9") )

donors <- select(d, disease_group, sex, site_of_motor_onset, duration, external_subject_id, platform, age = age_at_death, prep, site = site_specimen_collected) %>% distinct()

als <- filter(donors, disease_group != "Control")

als %>% group_by(disease_group, site_of_motor_onset == "Bulbar") %>% tally()

als %>% group_by(disease_group) %>% summarise(dur = median(duration, na.rm = TRUE), min = min(duration,na.rm = TRUE), max = max(duration, na.rm = TRUE))

als %>% ggplot(aes(x = disease_group, y = duration)) + geom_boxplot() + ggpubr::stat_compare_means()

donors %>% group_by(disease_group) %>% summarise(dur = median(age, na.rm = TRUE), min = min(age, na.rm = TRUE), max = max(age, na.rm = TRUE))

donors %>% ggplot(aes(x = disease_group, y = age)) + geom_boxplot() + ggpubr::stat_compare_means()


```

