---
title: "Misc_Plots"
author: "Jack Humphrey"
date: "20/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

theme_jh <- function () { 
    theme_bw(base_size=10) %+replace% 
        theme(
          panel.grid = element_blank(),
          strip.background = element_blank(),
          #panel.border = element_blank(),
          axis.line = element_line(),
          #text = element_text(color = "black"), 
          strip.text = element_text(color = "black"),
          axis.text = element_text(colour = "black"),
            panel.background  = element_blank(),
            plot.background = element_rect(fill="white", colour=NA), 
            legend.background = element_rect(fill="transparent", colour=NA),
            legend.key = element_rect(fill="transparent", colour=NA), 
            axis.line.y = element_line(), strip.text.x = element_text(face = "bold", margin = margin(t = 2,r = 0,b = 2,l=0))
        )
}


```

Motor neuron marker genes expression 

```{r}

gene_meta <- read_tsv(here::here("data/misc/gencode.v30.tx2gene.tsv.gz") )%>%
  janitor::clean_names() %>%
  select(genename, geneid) %>%
  distinct() %>%
  mutate( geneid = str_split_fixed(geneid, "\\.", 2)[,1] )

support <- read_tsv(here::here("data/differential_expression/ALS/ALS_all_differential_expression_support.tsv"))

t <- "Cervical_Spinal_Cord"
inFile <- here::here( paste0("data/differential_expression/ALS/", t, ".RData"))
load(inFile)
  
support_loc <- left_join(support_loc, tech_loc, by = "sample")

load( here::here("data/feb_2020/gene_tpm_no_tags.RData") )

genes_tpm$gene <- gene_meta$genename[match(row.names(genes_tpm), gene_meta$geneid)]

mn_genes <- filter(genes_tpm, gene %in%  c("CHAT", "ISL1","MNX1" )) %>%
  pivot_longer(cols = !gene, names_to = "sample", values_to = "TPM") %>%
  left_join(support, by = "sample")

mn_markers <- mn_genes %>%
  filter(disease %in% c("Control", "ALS")) %>%
  mutate(tissue = gsub("_Spinal_Cord", "", tissue)) %>%
  ggplot(aes(x = disease, y = log2(TPM) )) + 
  geom_point(aes(colour = disease, group = disease), position = position_jitterdodge())  +
  geom_boxplot(fill = NA, outlier.color = NA, aes(group = paste(disease, gene) ) ) +
  facet_wrap(~gene + tissue) +
  geom_hline(yintercept = 0, linetype = 3) +
  guides(colour = FALSE) +
  theme_jh() +
  ggpubr::stat_compare_means(label = "p.format", label.x.npc = 0.33, label.y.npc = 0.9)


mn_markers

ggsave(filename = "../../ALS_SC/plots/motor_neuron_marker_expression.pdf", plot = mn_markers, width = 7, height = 7)
ggsave(filename = "../../ALS_SC/plots/motor_neuron_marker_expression.png", plot = mn_markers, width = 7, height = 7)


```

## Putting together final file list 

Start with all spinal cord RNA and DNA samples
add column for those used in QTL analysis and for DEG analysis

```{r}

rna <- read_tsv(here::here("metadata/rna/rna_metadata_annotated.tsv"))
qtl <- read_tsv("../../ALS_SC/tables/all_qtl_samples_used.tsv")
deg <- read_tsv(here::here("data/differential_expression/ALS/ALS_all_differential_expression_support.tsv"))

sample_table <- filter(rna,
                           external_sample_id %in% unique( c(qtl$external_sample_id, deg$sample))
                           ) %>%
  mutate( DEG = external_sample_id %in% deg$sample,
          QTL = external_sample_id %in% qtl$external_sample_id) %>%
  select(
    rna_id = external_sample_id,
    dna_id = external_subject_id,
    neuro_bank_id, site_specimen_collected, tissue = tissue_clean, sex, subject_group, disease, site_of_motor_onset, age_of_onset = onset, age_at_death = death, mutations, library_prep = prep, seq_platform = platform, rin, c9orf72_repeat_size = c9_repeat_size,
    differential_expression = DEG, qtl_mapping = QTL) %>%
  mutate(c9orf72_repeat_size = as.numeric(c9orf72_repeat_size)) %>%
  arrange(tissue,dna_id)
    

write_tsv(sample_table, file = "../../ALS_SC/tables/all_samples_used_in_study.tsv")



```

